name: Insured Assurance GitHub Action - Workflow 
run-name: GitHub Actions - Insured Assurance
on: [push] 
jobs:
  Basic-Workflow: 
    runs-on: ubuntu-latest 
    steps: 
      - run: echo " Job is executing as part of Insured Assurance - Project 1 workflow"
